using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Text;
using System.Threading;
using System.Threading.Tasks;

namespace SimpleDI.TryGet
{
	/// <summary>
	/// Utility methods to make implementing TryGet... style methods slightly simpler.
	/// Takes inspiration from logic programming.
	/// </summary>
	public static class Logic
	{
		// (use alt + click & drag, or alt + shift + arrow keys, to make a rectangular selection & edit)
		[MethodImpl(MethodImplOptions.AggressiveInlining)] public static bool Fail() => false;
		[MethodImpl(MethodImplOptions.AggressiveInlining)] public static bool Fail<T1                                                                   >(out T1 o1                                                                                                                                                                                   ) { o1 = default;                                                                                                                                                                                                                          return false; }
		[MethodImpl(MethodImplOptions.AggressiveInlining)] public static bool Fail<T1, T2                                                               >(out T1 o1, out T2 o2                                                                                                                                                                        ) { o1 = default; o2 = default;                                                                                                                                                                                                            return false; }
		[MethodImpl(MethodImplOptions.AggressiveInlining)] public static bool Fail<T1, T2, T3                                                           >(out T1 o1, out T2 o2, out T3 o3                                                                                                                                                             ) { o1 = default; o2 = default; o3 = default;                                                                                                                                                                                              return false; }
		[MethodImpl(MethodImplOptions.AggressiveInlining)] public static bool Fail<T1, T2, T3, T4                                                       >(out T1 o1, out T2 o2, out T3 o3, out T4 o4                                                                                                                                                  ) { o1 = default; o2 = default; o3 = default; o4 = default;                                                                                                                                                                                return false; }
		[MethodImpl(MethodImplOptions.AggressiveInlining)] public static bool Fail<T1, T2, T3, T4, T5                                                   >(out T1 o1, out T2 o2, out T3 o3, out T4 o4, out T5 o5                                                                                                                                       ) { o1 = default; o2 = default; o3 = default; o4 = default; o5 = default;                                                                                                                                                                  return false; }
		[MethodImpl(MethodImplOptions.AggressiveInlining)] public static bool Fail<T1, T2, T3, T4, T5, T6                                               >(out T1 o1, out T2 o2, out T3 o3, out T4 o4, out T5 o5, out T6 o6                                                                                                                            ) { o1 = default; o2 = default; o3 = default; o4 = default; o5 = default; o6 = default;                                                                                                                                                    return false; }
		[MethodImpl(MethodImplOptions.AggressiveInlining)] public static bool Fail<T1, T2, T3, T4, T5, T6, T7                                           >(out T1 o1, out T2 o2, out T3 o3, out T4 o4, out T5 o5, out T6 o6, out T7 o7                                                                                                                 ) { o1 = default; o2 = default; o3 = default; o4 = default; o5 = default; o6 = default; o7 = default;                                                                                                                                      return false; }
		[MethodImpl(MethodImplOptions.AggressiveInlining)] public static bool Fail<T1, T2, T3, T4, T5, T6, T7, T8                                       >(out T1 o1, out T2 o2, out T3 o3, out T4 o4, out T5 o5, out T6 o6, out T7 o7, out T8 o8                                                                                                      ) { o1 = default; o2 = default; o3 = default; o4 = default; o5 = default; o6 = default; o7 = default; o8 = default;                                                                                                                        return false; }
		[MethodImpl(MethodImplOptions.AggressiveInlining)] public static bool Fail<T1, T2, T3, T4, T5, T6, T7, T8, T9                                   >(out T1 o1, out T2 o2, out T3 o3, out T4 o4, out T5 o5, out T6 o6, out T7 o7, out T8 o8, out T9 o9                                                                                           ) { o1 = default; o2 = default; o3 = default; o4 = default; o5 = default; o6 = default; o7 = default; o8 = default; o9 = default;                                                                                                          return false; }
		[MethodImpl(MethodImplOptions.AggressiveInlining)] public static bool Fail<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10                              >(out T1 o1, out T2 o2, out T3 o3, out T4 o4, out T5 o5, out T6 o6, out T7 o7, out T8 o8, out T9 o9, out T10 o10                                                                              ) { o1 = default; o2 = default; o3 = default; o4 = default; o5 = default; o6 = default; o7 = default; o8 = default; o9 = default; o10 = default;                                                                                           return false; }
		[MethodImpl(MethodImplOptions.AggressiveInlining)] public static bool Fail<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11                         >(out T1 o1, out T2 o2, out T3 o3, out T4 o4, out T5 o5, out T6 o6, out T7 o7, out T8 o8, out T9 o9, out T10 o10, out T11 o11                                                                 ) { o1 = default; o2 = default; o3 = default; o4 = default; o5 = default; o6 = default; o7 = default; o8 = default; o9 = default; o10 = default; o11 = default;                                                                            return false; }
		[MethodImpl(MethodImplOptions.AggressiveInlining)] public static bool Fail<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12                    >(out T1 o1, out T2 o2, out T3 o3, out T4 o4, out T5 o5, out T6 o6, out T7 o7, out T8 o8, out T9 o9, out T10 o10, out T11 o11, out T12 o12                                                    ) { o1 = default; o2 = default; o3 = default; o4 = default; o5 = default; o6 = default; o7 = default; o8 = default; o9 = default; o10 = default; o11 = default; o12 = default;                                                             return false; }
		[MethodImpl(MethodImplOptions.AggressiveInlining)] public static bool Fail<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13               >(out T1 o1, out T2 o2, out T3 o3, out T4 o4, out T5 o5, out T6 o6, out T7 o7, out T8 o8, out T9 o9, out T10 o10, out T11 o11, out T12 o12, out T13 o13                                       ) { o1 = default; o2 = default; o3 = default; o4 = default; o5 = default; o6 = default; o7 = default; o8 = default; o9 = default; o10 = default; o11 = default; o12 = default; o13 = default;                                              return false; }
		[MethodImpl(MethodImplOptions.AggressiveInlining)] public static bool Fail<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14          >(out T1 o1, out T2 o2, out T3 o3, out T4 o4, out T5 o5, out T6 o6, out T7 o7, out T8 o8, out T9 o9, out T10 o10, out T11 o11, out T12 o12, out T13 o13, out T14 o14                          ) { o1 = default; o2 = default; o3 = default; o4 = default; o5 = default; o6 = default; o7 = default; o8 = default; o9 = default; o10 = default; o11 = default; o12 = default; o13 = default; o14 = default;                               return false; }
		[MethodImpl(MethodImplOptions.AggressiveInlining)] public static bool Fail<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15     >(out T1 o1, out T2 o2, out T3 o3, out T4 o4, out T5 o5, out T6 o6, out T7 o7, out T8 o8, out T9 o9, out T10 o10, out T11 o11, out T12 o12, out T13 o13, out T14 o14, out T15 o15             ) { o1 = default; o2 = default; o3 = default; o4 = default; o5 = default; o6 = default; o7 = default; o8 = default; o9 = default; o10 = default; o11 = default; o12 = default; o13 = default; o14 = default; o15 = default;                return false; }
		[MethodImpl(MethodImplOptions.AggressiveInlining)] public static bool Fail<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16>(out T1 o1, out T2 o2, out T3 o3, out T4 o4, out T5 o5, out T6 o6, out T7 o7, out T8 o8, out T9 o9, out T10 o10, out T11 o11, out T12 o12, out T13 o13, out T14 o14, out T15 o15, out T16 o16) { o1 = default; o2 = default; o3 = default; o4 = default; o5 = default; o6 = default; o7 = default; o8 = default; o9 = default; o10 = default; o11 = default; o12 = default; o13 = default; o14 = default; o15 = default; o16 = default; return false; }
	}
}

//*/